const ParkingCycle = require("../models/ParkingCycle");
const ParkingAssignment = require("../models/ParkingAssignment");

const {
  sendMessage,
} = require("./whatsappService");

async function sendActiveCycleNotifications() {
  // ============================
  // Active Cycle
  // ============================

  const activeCycle =
    await ParkingCycle.findOne({
      status: "ACTIVE",
    });

  if (!activeCycle) {
    throw new Error(
      "No active parking cycle found."
    );
  }

  // ============================
  // Active Assignments
  // ============================

  const assignments =
    await ParkingAssignment.find({
      cycleId: activeCycle._id,
      assignmentStatus: "ACTIVE",
    })
      .populate("flatId")
      .populate("vehicleId")
      .populate("slotId");

  if (!assignments.length) {
    throw new Error(
      "No parking assignments found."
    );
  }

  const startDate =
    new Date(
      activeCycle.startDate
    ).toLocaleDateString(
      "en-IN",
      {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }
    );

  const endDate =
    new Date(
      activeCycle.endDate
    ).toLocaleDateString(
      "en-IN",
      {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }
    );

  let sent = 0;
  let failed = 0;

  const errors = [];

  // ============================
  // Send One By One
  // ============================

  for (const assignment of assignments) {
    try {
      const flat =
        assignment.flatId;

      const vehicle =
        assignment.vehicleId;

      const slot =
        assignment.slotId;

      // ------------------------

      if (
        !flat ||
        !flat.contactNumber
      ) {
        failed++;

        errors.push({
          flat:
            flat?.flatNumber ||
            "Unknown",
          reason:
            "Missing contact number",
        });

        continue;
      }

      // ------------------------

      let slotDisplay = "";

      if (
        assignment.parkingType ===
        "OUTSIDE"
      ) {
        slotDisplay =
          "Outside Parking Area";
      } else {
        slotDisplay = slot.slotNumber;
      }

      // ------------------------

      const message = `🏠 *SIDDH-A Society*

Dear *${flat.ownerName}*,

This is a reminder of your parking allocation for the current parking cycle.

━━━━━━━━━━━━━━━━━━

🏢 *Flat*
${flat.flatNumber}

🚗 *Vehicle*
${vehicle.vehicleNumber}

📍 *Parking Type*
${assignment.parkingType}

🅿 *Assigned Slot*
${slotDisplay}

📅 *Cycle*
${activeCycle.cycleName}

📆 *Duration*
${startDate} - ${endDate}

━━━━━━━━━━━━━━━━━━

Please ensure your vehicle is parked only in the assigned location throughout this cycle.

If you notice any discrepancy, kindly contact the society administrator.

_This is an automated message generated by ParkFair._

Thank you.

Have a wonderful day. 😊`;

      // ------------------------

      await sendMessage(
        flat.contactNumber,
        message
      );

      sent++;

      console.log(
        `✅ Sent -> Flat ${flat.flatNumber}`
      );

      // Wait 5 seconds
      await new Promise(
        (resolve) =>
          setTimeout(
            resolve,
            5000
          )
      );
    } catch (err) {
      failed++;

      console.error(
        `❌ Failed -> ${assignment.flatId?.flatNumber}`,
        err.message
      );

      errors.push({
        flat:
          assignment.flatId
            ?.flatNumber ||
          "Unknown",

        reason:
          err.message,
      });
    }
  }

  // ============================
  // Summary
  // ============================

  console.log("");

  console.log(
    "===================================="
  );

  console.log(
    "ParkFair Notification Summary"
  );

  console.log(
    "===================================="
  );

  console.log(
    `Cycle  : ${activeCycle.cycleName}`
  );

  console.log(
    `Total  : ${assignments.length}`
  );

  console.log(
    `Sent   : ${sent}`
  );

  console.log(
    `Failed : ${failed}`
  );

  console.log(
    "===================================="
  );

  return {
    success: true,

    cycle:
      activeCycle.cycleName,

    total:
      assignments.length,

    sent,

    failed,

    errors,
  };
}
async function previewActiveCycleNotifications() {
  const activeCycle =
    await ParkingCycle.findOne({
      status: "ACTIVE",
    });

  if (!activeCycle) {
    throw new Error(
      "No active parking cycle found."
    );
  }

  const assignments =
    await ParkingAssignment.find({
      cycleId: activeCycle._id,
      assignmentStatus: "ACTIVE",
    })
      .populate("flatId")
      .populate("vehicleId")
      .populate("slotId");

  const startDate =
    new Date(
      activeCycle.startDate
    ).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });

  const endDate =
    new Date(
      activeCycle.endDate
    ).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });

  const preview = assignments.map(
    (assignment) => {
      const flat = assignment.flatId;
      const vehicle =
        assignment.vehicleId;
      const slot = assignment.slotId;

      let slotDisplay =
        assignment.parkingType ===
        "OUTSIDE"
          ? "Outside Parking Area"
          : slot.slotNumber;

      const message = `🏠 *SIDDH-A Society*

Dear *${flat.ownerName}*,

Your parking allocation for the current parking cycle is as follows.

━━━━━━━━━━━━━━━━━━

🏢 *Flat*
${flat.flatNumber}

🚗 *Vehicle*
${vehicle.vehicleNumber}

📍 *Parking Type*
${assignment.parkingType}

🅿 *Assigned Slot*
${slotDisplay}

📅 *Cycle*
${activeCycle.cycleName}

📆 *Duration*
${startDate} - ${endDate}

━━━━━━━━━━━━━━━━━━

Please ensure your vehicle is parked only in the assigned location throughout this cycle.

If you notice any discrepancy, kindly contact the society administrator.

_This is an automated notification from the SIDDH-A Society Parking Management System._

Thank you.

Have a wonderful day. 😊`;

      return {
        flat: flat.flatNumber,
        owner: flat.ownerName,
        phone: flat.contactNumber,
        parking: assignment.parkingType,
        slot: slotDisplay,
        vehicle: vehicle.vehicleNumber,
        message,
      };
    }
  );

  return {
    success: true,
    total: preview.length,
    data: preview,
  };
}

module.exports = {
  sendActiveCycleNotifications,
  previewActiveCycleNotifications,
};